import assert from 'node:assert/strict';
import { test } from 'node:test';
import { Readable } from 'node:stream';
import { isolatedRedis } from '../helpers/isolated-redis';

test('encrypted transactional email queue, dedupe, retries, private recovery and webhook isolation', async () => {
  process.env.GATEWAY_KMS_KEY = 'b'.repeat(64);
  process.env.RESEND_API_KEY = 're_isolated_test';
  process.env.RESEND_FROM_EMAIL = 'support@contact.founderpostai.com';
  process.env.STRIPE_SECRET_KEY = 'sk_test_isolated';
  process.env.STRIPE_PRICE_PRO = 'price_email_pro';
  process.env.STRIPE_WEBHOOK_SECRET = 'whsec_email_test';
  process.env.CRON_SECRET = 'cron-isolated-secret';
  const close = await isolatedRedis();
  const originalFetch = globalThis.fetch;
  const sends: { id: string; body: any }[] = [];
  let providerStatus = 200;
  globalThis.fetch = async (input, options) => {
    if (String(input) !== 'https://api.resend.com/emails') return originalFetch(input, options);
    const headers = options!.headers as Record<string, string>;
    assert.equal(headers.Authorization, 'Bearer re_isolated_test');
    sends.push({ id: headers['Idempotency-Key'], body: JSON.parse(String(options!.body)) });
    return new Response(JSON.stringify(providerStatus === 200 ? { id: 'email_test_accepted' } : { name: 'validation_error', message: 'Sensitive body deliberately not logged' }), { status: providerStatus });
  };
  const response = () => ({ code: 200, body: null as any, headers: {} as any, setHeader(k: string, v: string) { this.headers[k] = v; }, status(code: number) { this.code = code; return this; }, json(body: any) { this.body = body; return this; }, end() { return this; } });
  try {
    const { redis, getJSON } = await import('../../src/lib/gateway/redis');
    const mail = await import('../../src/lib/transactional-email');
    const purchases = await import('../../src/lib/purchase-email');
    assert.equal(mail.normalizedEmail(' ALEX@EXAMPLE.COM '), 'alex@example.com');
    assert.equal(mail.normalizedEmail('alex@example.com\nBcc: other@example.com'), null);
    const receipt = { sessionId: 'cs_test_email', subscriptionId: 'sub_email', email: 'ALEX@example.com', plan: 'pro', licenseKey: 'AISP-AAAA-BBBB-CCCC' };
    const jobs = await Promise.all(Array.from({ length: 8 }, () => purchases.preparePurchaseEmail(receipt)));
    assert.equal(new Set(jobs).size, 1);
    const id = jobs[0]!;
    const queued = await redis('GET', `transactional-email:${id}`);
    assert.ok(!queued.includes('alex@example.com') && !queued.includes(receipt.licenseKey), 'Queued addresses, license and receipt URLs are encrypted');
    assert.equal(await redis('ZCARD', 'transactional-email:pending'), 1);
    await Promise.all(Array.from({ length: 8 }, () => mail.deliverEmail(id)));
    assert.equal(sends.length, 1, 'Concurrent deliveries claim only one sender lease');
    assert.equal(sends[0].body.from, 'FounderPostAI <support@contact.founderpostai.com>');
    assert.equal(sends[0].body.to, 'alex@example.com');
    assert.match(sends[0].body.text, /AI Suite → SEO Pro/);
    assert.match(sends[0].body.text, /https:\/\/founderpostai.com\/thanks\?session_id=cs_test_email/);
    assert.equal((await getJSON<any>(`transactional-email:${id}`)).encrypted, undefined, 'Accepted emails no longer retain message content');
    await purchases.preparePurchaseEmail(receipt);
    await mail.deliverEmail(id);
    assert.equal(sends.length, 1, 'Receipt refresh cannot resend a purchase email');

    const retryId = (await purchases.preparePurchaseEmail({ ...receipt, subscriptionId: 'sub_retry' }))!;
    providerStatus = 403;
    assert.equal(await mail.deliverEmail(retryId), 'queued', 'Unverified domain keeps the message recoverable');
    const failed = await getJSON<any>(`transactional-email:${retryId}`);
    assert.equal(failed.lastError, 'resend_http_403');
    assert.ok(failed.encrypted);
    const failedAttempt = sends.at(-1)!;
    providerStatus = 200;
    assert.equal(await mail.deliverEmail(retryId, failed.nextAttempt + 1), 'sent');
    assert.equal(sends.at(-1)!.id, failedAttempt.id, 'Retries reuse the Resend idempotency key');
    assert.deepEqual(sends.at(-1)!.body, failedAttempt.body, 'Retries send identical content');

    const { default: recover } = await import('../../src/pages/api/purchase/recover');
    const req = (email: string, ip = '192.0.2.1') => ({ method: 'POST', body: { email }, headers: { 'x-forwarded-for': ip } }) as any;
    const known = response();
    await recover(req('alex@example.com'), known as any);
    const unknown = response();
    const beforeUnknown = sends.length;
    await recover(req('not-a-customer@example.com'), unknown as any);
    assert.equal(known.code, 202);
    assert.deepEqual(known.body, unknown.body, 'Recovery does not reveal whether an email is registered');
    assert.equal(sends.length, beforeUnknown, 'Unknown addresses cannot be used as an email relay');
    assert.ok(!JSON.stringify(known.body).includes('cs_test_email'));
    const recoveryMessage = sends.find(send => send.body.subject === 'Recover your FounderPostAI purchases')!;
    assert.equal(recoveryMessage.body.to, 'alex@example.com');
    assert.match(recoveryMessage.body.text, /AISP-AAAA-BBBB-CCCC/);
    await recover(req('alex@example.com'), response() as any);
    await recover(req('alex@example.com'), response() as any);
    const limited = response();
    await recover(req('alex@example.com', '192.0.2.2'), limited as any);
    assert.equal(limited.code, 429, 'Per-address rate limits survive IP changes');

    const expiredId = mail.emailDigest('expired-test');
    await mail.queueEmail(expiredId, mail.emailMessage('alex@example.com', 'Expired test', 'test'));
    const sendsBeforeExpiry = sends.length;
    await mail.deliverEmail(expiredId, Date.now() + 31 * 86400000);
    assert.equal(await redis('GET', `transactional-email:${expiredId}`), null);
    assert.equal(sends.length, sendsBeforeExpiry, 'Old pending payloads expire rather than retry indefinitely');

    const { stripe } = await import('../../src/lib/stripe');
    const subscription: any = { id: 'sub_webhook_email', customer: 'cus_email', status: 'active', metadata: {}, items: { data: [{ price: { id: 'price_email_pro' } }] } };
    stripe.subscriptions.retrieve = (async () => structuredClone(subscription)) as any;
    stripe.subscriptions.update = (async (_id: string, input: any) => { subscription.metadata = input.metadata; return subscription; }) as any;
    stripe.checkout.sessions.retrieve = (async () => ({ id: 'cs_test_webhook_email', status: 'complete', payment_status: 'paid', customer_details: { email: 'buyer@example.com' }, subscription: subscription.id, line_items: { data: [{ price: { id: 'price_email_pro' } }] } })) as any;
    const { default: webhook } = await import('../../src/pages/api/webhooks/stripe');
    const payload = JSON.stringify({ type: 'checkout.session.completed', data: { object: { id: 'cs_test_webhook_email' } } });
    const signature = stripe.webhooks.generateTestHeaderString({ payload, secret: process.env.STRIPE_WEBHOOK_SECRET! });
    providerStatus = 403;
    const webhookResult = response();
    await webhook(Object.assign(Readable.from([Buffer.from(payload)]), { method: 'POST', headers: { 'stripe-signature': signature } }) as any, webhookResult as any);
    assert.equal(webhookResult.code, 500, 'Stripe is asked to retry pending email work');
    assert.ok(subscription.metadata.license_key, 'Email failure does not roll back the paid license');
    const { default: license } = await import('../../src/pages/api/license');
    const purchaseResult = response();
    await license({ method: 'GET', query: { session_id: 'cs_test_webhook_email' } } as any, purchaseResult as any);
    assert.equal(purchaseResult.code, 200, 'Paid download access remains available while email is queued');
    assert.equal(purchaseResult.body.emailDelivery, 'queued');
    assert.ok(purchaseResult.body.downloadUrl);
    const { default: cron } = await import('../../src/pages/api/cron/email-outbox');
    const denied = response();
    await cron({ method: 'GET', headers: {} } as any, denied as any);
    assert.equal(denied.code, 401);
    const allowed = response();
    await cron({ method: 'GET', headers: { authorization: `Bearer ${process.env.CRON_SECRET}` } } as any, allowed as any);
    assert.equal(allowed.code, 200);
  } finally { globalThis.fetch = originalFetch; await close(); }
});
